// src/utils/emailService.js
// Consolidated email service - all email functions in one place
// Generated by Phase 2 refactoring (2026-03-31)

import emailjs from "emailjs-com";
import { sendEmailApi } from "./hooks/api/emailApi";
import { requestEmailTemplates } from "./constants/requestEmailTemplates";

// ============================================================
// Configuration
// ============================================================
const EMAILJS_USER_ID = "xlmGc2aT4GDUYDQWT";
const EMAILJS_SERVICE_ID = "service_wka3qqh";

// Initialize once
emailjs.init(EMAILJS_USER_ID);

// ============================================================
// Core send function - all others delegate to this
// ============================================================
export async function sendEmail(templateId, templateParams, onSuccess = null, onError = null) {
  return emailjs
    .send(EMAILJS_SERVICE_ID, templateId, templateParams)
    .then((response) => {
      if (typeof onSuccess === "function") onSuccess(response);
      return response;
    })
    .catch((err) => {
      console.error("Failed to send email:", err);
      if (typeof onError === "function") onError(err);
      throw err;
    });
}

// ============================================================
// Recruitment & HR email functions (from emailSenderHelper.js)
// ============================================================

export async function sendWelcomeEmail(
  templateParams,
  emailPayload,
  onSuccess = null,
  onError = null
) {
  const emailBody = `<html>
    <body>
      <div style="font-family: Arial, sans-serif; background-color: #f4f4f4; color: #333; padding: 20px;">
          <div style="background-color: #ffffff; border-radius: 8px; padding: 30px; max-width: 600px; margin: 0 auto; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);">
              <!-- English Version -->
              <div style="text-align: center; color: #2c3e50;">
                  <h2>Welcome to MRNA - ${emailPayload.name}</h2>
              </div>
          </div>
      </div>
    </body>
  </html>`;

  const payload = {
    subject: templateParams.subject || "Welcome to MRNA",
    html_body: emailBody,
    email: emailPayload.email,
  };

  try {
    const res = await sendEmailApi(payload);
    if (typeof onSuccess === "function") onSuccess(res);
    return res;
  } catch (err) {
    if (typeof onError === "function") onError(err);
    throw err;
  }
}

/**
 * -------------------
 * Candidate Verification
 * -------------------
 */
export async function sendCandidateVerificationEmail(
  template,
  templateParams,
  onSuccess = null,
  onError = null
) {
  let emailbody = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Verify your email</title>
  </head>
  <body style="font-family: Arial, Helvetica, sans-serif; color: #222; line-height: 1.4; margin: 0; padding: 0;">
    <table width="100%" cellpadding="0" cellspacing="0" role="presentation">
      <tr>
        <td align="center" style="padding: 24px;">
          <table width="600" cellpadding="0" cellspacing="0" role="presentation" style="border: 1px solid #e6e6e6; border-radius: 8px; overflow: hidden;">
            <tr>
              <td style="background:#0b6cff; padding: 20px 24px; color: #fff; text-align: left;">
                <h1 style="margin: 0; font-size: 20px;">Welcome to MRNA!</h1>
              </td>
            </tr>
            <tr>
              <td style="padding: 28px;">
                <p style="margin: 0 0 16px 0; font-size: 15px;">Hi <strong>${templateParams.name}</strong>,</p>

                <p style="margin: 0 0 20px 0; font-size: 15px;">
                  Thanks for creating an account with MRNA. Please verify your email address to complete setup and secure your account.
                </p>

                <p style="text-align: center; margin: 0 0 24px 0;">
                  <a href="${templateParams.canidate_sigup}" style="display: inline-block; padding: 12px 20px; background: #0b6cff; color: #fff; text-decoration: none; border-radius: 6px; font-weight: 600;">Verify Email</a>
                </p>

                <p style="margin: 0 0 16px 0; font-size: 13px; color: #666;">
                  If the button does not work, copy and paste the following link into your browser:
                  <br>
                  <a href="{{verification_link}}" style="color: #0b6cff; word-break: break-all;">{{verification_link}}</a>
                </p>

                <p style="margin: 20px 0 0 0; font-size: 13px; color: #666;">
                  This link will expire in 24 hours. If you did not sign up for MRNA, you can ignore this email.
                </p>

                <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">

                <p style="margin: 0; font-size: 13px; color: #666;">
                  Need help? Reply to this email or contact <a href="mailto:${templateParams.support_email}" style="color: #0b6cff;">support@mrna.example</a>.
                </p>

                <p style="margin: 18px 0 0 0; font-size: 13px; color: #999;">
                  &copy; <span id="year">2025</span> MRNA. All rights reserved.
                </p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>
`;
  const payload = {
    subject: templateParams.subject || "Candidate Verification – MRNA",
    html_body: emailbody,
    email: templateParams.email,
  };

  try {
    const res = await sendEmailApi(payload);
    if (typeof onSuccess === "function") onSuccess(res);
    return res;
  } catch (err) {
    if (typeof onError === "function") onError(err);
    throw err;
  }
}

/**
 * -------------------
 * Offer Email
 * -------------------
 */
export const sendOfferEmail = async ({
  candidateName,
  email,
  jobTitle,
  portalLink,
  requiredDocuments,
  onSuccess = null,
  onError = null,
}) => {
  const emailBody = `
  <html>
    <body>
      <div style="font-family: Arial, sans-serif; background-color: #f4f4f4; color: #333; padding: 20px;">
          <div style="background-color: #ffffff; border-radius: 8px; padding: 30px; max-width: 600px; margin: 0 auto; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);">
              
              <!-- Arabic Version -->
              <div style="text-align: center; color: #2c3e50;">
                  <h2>عرض الوظيفة &ndash;  في MRNA</h2>
              </div>
              <p>عزيزي/عزيزتي ${candidateName},</p>
              
              <p>للمضي قدمًا في عرضك، يرجى اتباع التعليمات أدناه:</p>
              <ul>
                  <li>قم بتسجيل الدخول إلى بوابتك على  للوصول إلى عرض الوظيفة.</li>
                  <li>قم بتنزيل عرض الوظيفة، وراجعه بعناية ووقعه.</li>
                  <li>قم بتحميل عرض الوظيفة الموقع مرة أخرى إلى البوابة.</li>
                  <li>بالإضافة إلى ذلك، يرجى تحميل المستندات المطلوبة الأخرى: (مثلاً: إثبات الهوية، الشهادات) إلى البوابة.</li>
              </ul>
              
              <p>نطلب منك إتمام العملية في غضون 30 يومًا. إذا كان لديك أي أسئلة أو تحتاج إلى مساعدة، فلا تتردد في الاتصال بنا على support@mrna.sa.</p>
              <p>نتطلع إلى ردك الإيجابي ونحن متحمسون لاحتمالية انضمامك إلى فريقنا في MRNA!</p>
              <p>مع أطيب التحيات,<br>مدير الموارد البشرية<br>MRNA<br>support@mrna.sa</p>
              
              <div style="text-align: center; font-size: 12px; color: #777; margin-top: 30px;">
                  <p>شكرًا لاهتمامك بالانضمام إلى mrna.sa.</p>
              </div>

              <!-- English Version -->
              <div style="text-align: center; color: #2c3e50;">
                  <h2>Job Offer &ndash; at MRNA</h2>
              </div>
              <p>Dear ${candidateName},</p>
              
              <p>To proceed with your offer, please follow the instructions below:</p>
              <ul>
                  <li>Login to your portal to access your offer letter.</li>
                  <li>Download your offer letter, carefully review and sign it.</li>
                  <li>Upload the signed offer letter back to the portal.</li>
                  <li>Additionally, please upload the following required documents: (e.g., ID proof, certifications) (e.g., ID proof, certifications, etc.) to the portal.</li>
              </ul>
              
              <p>We kindly request that you complete the process within 30-days. Should you have any questions or need assistance, feel free to contact us at support@mrna.sa.</p>
              <p>We look forward to your positive response and are excited about the possibility of you joining our team at MRNA!</p>
              <p>Best regards,<br>HR Manager<br>MRNA<br>support@mrna.sa</p>
              
              <div style="text-align: center; font-size: 12px; color: #777; margin-top: 30px;">
                  <p>Thank you for your interest in joining mrna.sa.</p>
              </div>

          </div>
      </div>
    </body>
  </html>
`;
  const payload = {
    subject: "Job Offer Letter – MRNA | خطاب عرض عمل – MRNA",
    html_body: emailBody,
    email,
  };

  try {
    const res = await sendEmailApi(payload);
    if (typeof onSuccess === "function") onSuccess(res);
    return res;
  } catch (err) {
    if (typeof onError === "function") onError(err);
    throw err;
  }
};

/**
 * -------------------
 * Contract Email
 * -------------------
 */
export const sendContractEmail = async ({
  candidateName,
  email,
  onSuccess = null,
  onError = null,
}) => {
  const emailBody = `
    <html>
      <body>
        <div style="font-family: Arial, sans-serif; background-color: #f4f4f4; color: #333; padding: 20px;">
            <div style="background-color: #ffffff; border-radius: 8px; padding: 30px; max-width: 600px; margin: 0 auto; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);">
                
                <!-- Arabic Version -->
                <div style="text-align: center; color: #2c3e50;">
                    <h2>عرض العقد - MRNA</h2>
                </div>
                <p>عزيزي/عزيزتي ${candidateName},</p>
                <p>نحن سعداء بتقديم عرض عقد رسمي لك في MRNA. بعد مراجعة مؤهلاتك وأدائك خلال عملية المقابلة، نحن واثقون من أنك ستكون إضافة قيمة لفريقنا.</p>
                
                <p>للمضي قدمًا في عقدك، يرجى اتباع الخطوات أدناه:</p>
                <ul>
                    <li>قم بتسجيل الدخول إلى بوابتك للوصول إلى عقدك.</li>
                    <li>قم بتنزيل عقدك، وراجع بعناية ووقعه.</li>
                    <li>قم بتحميل العقد الموقع مرة أخرى إلى البوابة.</li>
                    <li>بالإضافة إلى ذلك، يرجى تحميل المستندات المطلوبة التالية: (مثلاً: إثبات الهوية، الشهادات) (مثل إثبات الهوية، والشهادات، وما إلى ذلك) إلى البوابة.</li>
                </ul>
                
                <p>يرجى التأكد من إتمام العملية في غضون 30 يومًا القادمة لتأكيد قبولك للعرض. إذا كان لديك أي أسئلة أو تحتاج إلى مساعدة، فلا تتردد في الاتصال بنا على support@mrna.sa.</p>
                <p>نحن متحمسون لاحتمالية انضمامك إلى فريقنا في MRNA ونتطلع إلى ردك الإيجابي.</p>

                <p>مع أطيب التحيات,<br>مدير الموارد البشرية<br>MRNA<br>support@mrna.sa</p>
                
                <div style="text-align: center; font-size: 12px; color: #777; margin-top: 30px;">
                    <p>شكرًا لاهتمامك بالانضمام إلى mrna.sa.</p>
                </div>

                <!-- English Version -->
                <div style="text-align: center; color: #2c3e50;">
                    <h2>Contract Offer - MRNA</h2>
                </div>
                <p>Dear ${candidateName},</p>
                <p>We are pleased to extend an official contract offer to you for the position at MRNA. After reviewing your qualifications and performance throughout the interview process, we are confident that you will be a valuable addition to our team.</p>
                
                <p>To proceed with your contract, please follow the steps below:</p>
                <ul>
                    <li>Login to your portal to access your contract letter.</li>
                    <li>Download your contract letter, carefully review and sign it.</li>
                    <li>Upload the signed contract letter back to the portal.</li>
                    <li>Additionally, please upload the following required documents: (e.g., ID proof, certifications) (e.g., ID proof, certifications, etc.) to the portal.</li>
                </ul>
                
                <p>Please ensure that you complete the process within the next 30 days to confirm your acceptance of the offer. If you have any questions or need assistance, feel free to contact us at support@mrna.sa.</p>

                <p>We are excited about the possibility of you joining our team at MRNA and look forward to your positive response.</p>

                <p>Best regards,<br>HR Manager<br>MRNA<br>support@mrna.sa</p>
                
                <div style="text-align: center; font-size: 12px; color: #777; margin-top: 30px;">
                    <p>Thank you for your interest in joining mrna.sa.</p>
                </div>

            </div>
        </div>
      </body>
    </html>
  `;

  const payload = {
    subject: "Contract Offer Letter – MRNA | خطاب عرض العقد – MRNA",
    html_body: emailBody,
    email,
  };

  try {
    const res = await sendEmailApi(payload);
    if (typeof onSuccess === "function") onSuccess(res);
    return res;
  } catch (err) {
    if (typeof onError === "function") onError(err);
    throw err;
  }
};

/**
 * -------------------
 * Offer Accepted
 * -------------------
 */
export const sendOfferAcceptedEmail = async ({
  candidateName,
  candidateEmail,
  jobTitle,
  acceptanceDate,
  email,
  onSuccess = null,
  onError = null,
}) => {
  const emailBody = `
    <html>
      <body>
        <div style="font-family: Arial, sans-serif; background-color: #f4f4f4; color: #333; padding: 20px;">
            <div style="background-color: #ffffff; border-radius: 8px; padding: 30px; max-width: 600px; margin: 0 auto; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);">
                
                <!-- Arabic Version -->
                <div class="header" style="text-align: center; color: #2c3e50;">
                    <h2>تم قبول عرض الوظيفة &ndash; ${candidateName} في MRNA</h2>
                </div>
                <p>عزيزي/عزيزتي فريق الموارد البشرية،</p>
                <p>نحن سعداء بإبلاغكم أن المرشح ${candidateName} قد قبل عرض الوظيفة للمنصب ${jobTitle} في MRNA.</p>

                <p>إليك التفاصيل:</p>
                <ul>
                    <li><strong>اسم المرشح:</strong> ${candidateName} - ${candidateEmail}</li>
                    <li><strong>تاريخ قبول العرض:</strong> ${acceptanceDate}</li>
                </ul>

                <p>يرجى متابعة الإجراءات التالية: التأكد من استلام المستندات النهائية من المرشح وتحديث سجلاتنا لتأكيد انضمامه إلى الفريق.</p>

                <p>إذا كان لديك أي أسئلة أو تحتاج إلى مزيد من المعلومات، يرجى الاتصال بنا على support@mrna.sa.</p>

                <p>مع أطيب التحيات,<br>مدير الموارد البشرية<br>MRNA<br>support@mrna.sa</p>

                <div class="footer" style="text-align: center; font-size: 12px; color: #777; margin-top: 30px;">
                    <p>شكرًا لاهتمامك في الانضمام إلى MRNA.</p>
                </div>

                <!-- English Version -->
                <div class="header" style="text-align: center; color: #2c3e50;">
                    <h2>Job Offer Accepted &ndash; ${candidateName} at MRNA</h2>
                </div>
                <p>Dear HR Team,</p>
                <p>We are pleased to inform you that the candidate ${candidateName} has accepted the job offer for the position of ${jobTitle} at MRNA.</p>

                <p>Here are the details:</p>
                <ul>
                    <li><strong>Candidate Name:</strong> ${candidateName} - ${candidateEmail}</li>
                    <li><strong>Acceptance Date:</strong> ${acceptanceDate}</li>
                </ul>

                <p>Please proceed with the next steps: Ensure that all final documentation is received from the candidate and update our records to confirm their onboarding to the team.</p>

                <p>If you have any questions or need further information, please feel free to contact us at support@mrna.sa.</p>

                <p>Best regards,<br>HR Manager<br>MRNA<br>support@mrna.sa</p>

                <div class="footer" style="text-align: center; font-size: 12px; color: #777; margin-top: 30px;">
                    <p>Thank you for your interest in joining MRNA.</p>
                </div>

            </div>
        </div>
      </body>
    </html>
`;

  const payload = {
    subject: "Job Offer Accepted – MRNA | قبول عرض الوظيفة – MRNA",
    html_body: emailBody,
    email,
  };

  return sendEmailApi(payload)
    .then((res) => {
      if (onSuccess) onSuccess(res);
      return res;
    })
    .catch((err) => {
      if (onError) onError(err);
      throw err;
    });
};

/**
 * -------------------
 * Contract Accepted
 * -------------------
 */
export const sendContractAcceptedEmail = async ({
  candidateName,
  candidateEmail,
  email,
  onSuccess = null,
  onError = null,
}) => {
  const emailBody = `
  <html>
    <body>
      <div style="font-family: Arial, sans-serif; background-color: #f4f4f4; color: #333; padding: 20px;">
          <div style="background-color: #ffffff; border-radius: 8px; padding: 30px; max-width: 600px; margin: 0 auto; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);">
              
              <!-- Arabic Version -->
              <div class="header" style="text-align: center; color: #2c3e50;">
                  <h2>تم قبول العقد &ndash; ${candidateName} في MRNA</h2>
              </div>
              <p>عزيزي/عزيزتي فريق الموارد البشرية،</p>
              <p>نحن سعداء بإبلاغكم أن المرشح ${candidateName} قد قبل العقد.</p>

              <p>إليك التفاصيل:</p>
              <ul>
                  <li><strong>اسم المرشح:</strong> ${candidateName} - ${candidateEmail}</li>
              </ul>

              <p>يرجى متابعة الإجراءات التالية: التأكد من استلام المستندات النهائية من المرشح وتحديث سجلاتنا لتأكيد انضمامه إلى الفريق.</p>

              <p>إذا كان لديك أي أسئلة أو تحتاج إلى مزيد من المعلومات، يرجى الاتصال بنا على support@mrna.sa.</p>

              <p>مع أطيب التحيات,<br>مدير الموارد البشرية<br>MRNA<br>support@mrna.sa</p>

              <div class="footer" style="text-align: center; font-size: 12px; color: #777; margin-top: 30px;">
                  <p>شكرًا لاهتمامك في الانضمام إلى MRNA.</p>
              </div>

              <!-- English Version -->
              <div class="header" style="text-align: center; color: #2c3e50;">
                  <h2>Contract Accepted &ndash; ${candidateName} at MRNA</h2>
              </div>
              <p>Dear HR Team,</p>
              <p>We are pleased to inform you that the candidate ${candidateName} has accepted the contract.</p>

              <p>Here are the details:</p>
              <ul>
                  <li><strong>Candidate Name:</strong> ${candidateName} - ${candidateEmail}</li>
              </ul>

              <p>Please proceed with the next steps: Ensure that all final documentation is received from the candidate and update our records to confirm their onboarding to the team.</p>

              <p>If you have any questions or need further information, please feel free to contact us at support@mrna.sa.</p>

              <p>Best regards,<br>HR Manager<br>MRNA<br>support@mrna.sa</p>

              <div class="footer" style="text-align: center; font-size: 12px; color: #777; margin-top: 30px;">
                  <p>Thank you for your interest in joining MRNA.</p>
              </div>

          </div>
      </div>
    </body>
  </html>
`;

  const payload = {
    subject: "Contract Accepted – MRNA | قبول العقد – MRNA",
    html_body: emailBody,
    email,
  };

  return sendEmailApi(payload)
    .then((res) => {
      if (onSuccess) onSuccess(res);
      return res;
    })
    .catch((err) => {
      if (onError) onError(err);
      throw err;
    });
};

/**
 * -------------------
 * Offer Rejected
 * -------------------
 */
export const sendOfferRejectedEmail = async ({
  candidateName,
  candidateEmail,
  jobTitle,
  rejectionDate,
  email,
  onSuccess = null,
  onError = null,
}) => {
  const emailBody = `
    <html>
      <body>
        <div style="font-family: Arial, sans-serif; background-color: #f4f4f4; color: #333; padding: 20px;">
            <div style="background-color: #ffffff; border-radius: 8px; padding: 30px; max-width: 600px; margin: 0 auto; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);">
                
                <!-- Arabic Version -->
                <div class="header" style="text-align: center; color: #2c3e50;">
                    <h2>تم رفض عرض الوظيفة &ndash; ${candidateName} في MRNA</h2>
                </div>
                <p>عزيزي/عزيزتي فريق الموارد البشرية،</p>
                <p>نود إعلامكم أن المرشح ${candidateName} قد رفض عرض الوظيفة للمنصب ${jobTitle} في MRNA.</p>

                <p>إليك التفاصيل:</p>
                <ul>
                    <li><strong>اسم المرشح:</strong> ${candidateName} - ${candidateEmail}</li>
                    <li><strong>المنصب:</strong> ${jobTitle}</li>
                    <li><strong>تاريخ رفض العرض:</strong> ${rejectionDate}</li>
                </ul>

                <p>يرجى متابعة الإجراءات التالية: تحديث سجلاتنا بناءً على قرار المرشح وبدء البحث عن بديل له في المنصب.</p>

                <p>إذا كان لديك أي أسئلة أو تحتاج إلى مزيد من المعلومات، يرجى الاتصال بنا على support@mrna.sa.</p>

                <p>مع أطيب التحيات,<br>مدير الموارد البشرية<br>MRNA<br>support@mrna.sa</p>

                <div class="footer" style="text-align: center; font-size: 12px; color: #777; margin-top: 30px;">
                    <p>شكرًا لاهتمامك في الانضمام إلى MRNA.</p>
                </div>

                <!-- English Version -->
                <div class="header" style="text-align: center; color: #2c3e50;">
                    <h2>Job Offer Rejected &ndash; ${candidateName} at MRNA</h2>
                </div>
                <p>Dear HR Team,</p>
                <p>We regret to inform you that the candidate ${candidateName} has rejected the job offer for the position of ${jobTitle} at MRNA.</p>

                <p>Here are the details:</p>
                <ul>
                    <li><strong>Candidate Name:</strong> ${candidateName} - ${candidateEmail}</li>
                    <li><strong>Job Title:</strong> ${jobTitle}</li>
                    <li><strong>Rejection Date:</strong> ${rejectionDate}</li>
                </ul>

                <p>Please proceed with the next steps: Update our records based on the candidate's decision and start looking for an alternative candidate for the position.</p>

                <p>If you have any questions or need further information, please feel free to contact us at support@mrna.sa.</p>

                <p>Best regards,<br>HR Manager<br>MRNA<br>support@mrna.sa</p>

                <div class="footer" style="text-align: center; font-size: 12px; color: #777; margin-top: 30px;">
                    <p>Thank you for your interest in joining MRNA.</p>
                </div>

            </div>
        </div>
      </body>
    </html>
  `;

  const payload = {
    subject: "Job Offer Rejected – MRNA | تم رفض عرض الوظيفة – MRNA",
    html_body: emailBody,
    email,
  };

  return sendEmailApi(payload)
    .then((res) => {
      if (onSuccess) onSuccess(res);
      return res;
    })
    .catch((err) => {
      if (onError) onError(err);
      throw err;
    });
};

/**
 * -------------------
 * Contract Rejected
 * -------------------
 */
export const sendContractRejectedEmail = async ({
  candidateName,
  candidateEmail,
  email,
  onSuccess = null,
  onError = null,
}) => {
  const emailBody = `
    <html>
      <body>
        <div style="font-family: Arial, sans-serif; background-color: #f4f4f4; color: #333; padding: 20px;">
            <div style="background-color: #ffffff; border-radius: 8px; padding: 30px; max-width: 600px; margin: 0 auto; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);">
                
                <!-- Arabic Version -->
                <div class="header" style="text-align: center; color: #2c3e50;">
                    <h2>تم رفض العقد &ndash; ${candidateName} في MRNA</h2>
                </div>
                <p>عزيزي/عزيزتي فريق الموارد البشرية،</p>
                <p>نود إعلامكم أن المرشح ${candidateName} قد رفض العقد.</p>

                <p>إليك التفاصيل:</p>
                <ul>
                    <li><strong>اسم المرشح:</strong> ${candidateName} - ${candidateEmail}</li>
                </ul>

                <p>يرجى متابعة الإجراءات التالية: تحديث سجلاتنا بناءً على قرار المرشح وبدء البحث عن بديل له في المنصب.</p>

                <p>إذا كان لديك أي أسئلة أو تحتاج إلى مزيد من المعلومات، يرجى الاتصال بنا على support@mrna.sa.</p>

                <p>مع أطيب التحيات,<br>مدير الموارد البشرية<br>MRNA<br>support@mrna.sa</p>

                <div class="footer" style="text-align: center; font-size: 12px; color: #777; margin-top: 30px;">
                    <p>شكرًا لاهتمامك في الانضمام إلى MRNA.</p>
                </div>

                <!-- English Version -->
                <div class="header" style="text-align: center; color: #2c3e50;">
                    <h2>Contract Rejected &ndash; ${candidateName} at MRNA</h2>
                </div>
                <p>Dear HR Team,</p>
                <p>We regret to inform you that the candidate ${candidateName} has rejected the contract.</p>

                <p>Here are the details:</p>
                <ul>
                    <li><strong>Candidate Name:</strong> ${candidateName} - ${candidateEmail}</li>
                </ul>

                <p>Please proceed with the next steps: Update our records based on the candidate's decision and start looking for an alternative candidate for the position.</p>

                <p>If you have any questions or need further information, please feel free to contact us at support@mrna.sa.</p>

                <p>Best regards,<br>HR Manager<br>MRNA<br>support@mrna.sa</p>

                <div class="footer" style="text-align: center; font-size: 12px; color: #777; margin-top: 30px;">
                    <p>Thank you for your interest in joining MRNA.</p>
                </div>

            </div>
        </div>
      </body>
    </html>
  `;

  const payload = {
    subject: "Contract Rejected – MRNA | تم رفض العقد – MRNA",
    html_body: emailBody,
    email,
  };

  return sendEmailApi(payload)
    .then((res) => {
      if (onSuccess) onSuccess(res);
      return res;
    })
    .catch((err) => {
      if (onError) onError(err);
      throw err;
    });
};

/**
 * -------------------
 * Interview Emails (first, second, third, interviewer)
 * -------------------
 */
export const sendFirstInterviewEmail = async ({
  candidate_name,
  interview_date,
  interview_time,
  email,
  interviewTypeField,
  interviewUrlField,
  interviewLocationField,
  onSuccess = null,
  onError = null,
}) => {
  let emailBody = "";
  let subject =
    "First Interview Invitation – MRNA | دعوة للمقابلة الأولى – MRNA";

  // Normalize type to lowercase for safe matching
  const interviewType = interviewTypeField?.toLowerCase() || "";
  
  if (interviewType.includes("online")) {
    // ✅ Online template
    emailBody = `
      <html>
        <body style="font-family: Arial, sans-serif; color: #333; line-height:1.6;">
          <!-- Arabic Version -->
          <p>عزيزنا المرشح،</p>
          <p>نتواصل معك نحن إدارة توظيف شركة مرنة للتمويل لإجراء مقابلة عن بعد يوم (${interview_time}) الموافق ${interview_date}.</p>
          <p><strong>رابط المقابلة:</strong> ${interviewUrlField || "N/A"}</p>
          <p>مع الشكر.</p>

          <hr style="margin:20px 0;" />

          <!-- English Version -->
          <p>Dear Candidate,</p>
          <p>We are contacting you from the Recruitment Department at Marna Financing Company to conduct a virtual interview on <strong>${interview_time}</strong> corresponding to <strong>${interview_date}</strong>.</p>
          <p><strong>Interview Link:</strong> ${interviewUrlField || "N/A"}</p>
          <p>Thank you.</p>
        </body>
      </html>
    `;
  } else if (interviewType.includes("physical")) {
    // ✅ Physical template
    emailBody = `
      <html>
        <body style="font-family: Arial, sans-serif; color: #333; line-height:1.6;">
          <!-- Arabic Version -->
          <p>عزيزنا المرشح،</p>
          <p>نتواصل معك نحن إدارة توظيف شركة مرنة للتمويل لإجراء مقابلة حضورية يوم (${interview_time}) الموافق ${interview_date}.</p>
          <p><strong>موقع المقابلة:</strong> ${
            interviewLocationField || "N/A"
          }</p>
          <p>نأمل احضار السيرة الذاتية المحدثة.</p>
          <p>مع الشكر.</p>

          <hr style="margin:20px 0;" />

          <!-- English Version -->
          <p>Dear Candidate,</p>
          <p>We are contacting you from the Recruitment Department at Marna Financing Company to invite you for an in-person interview on <strong>${interview_time}</strong> corresponding to <strong>${interview_date}</strong>.</p>
          <p><strong>Interview Location:</strong> ${
            interviewLocationField || "N/A"
          }</p>
          <p>Please bring your updated resume with you.</p>
          <p>Thank you.</p>
        </body>
      </html>
    `;
  } else {
    // ✅ Fallback generic template
    emailBody = `
        <html>
        <body style="font-family: Arial, sans-serif; color: #333; line-height:1.6;">
          <!-- Arabic Version -->
          <p>عزيزنا المرشح،</p>
          <p>نتواصل معك نحن إدارة توظيف شركة مرنة للتمويل لإجراء مقابلة حضورية يوم (${interview_time}) الموافق ${interview_date}.</p>
          <p>نأمل احضار السيرة الذاتية المحدثة.</p>
          <p>مع الشكر.</p>

          <hr style="margin:20px 0;" />

          <!-- English Version -->
          <p>Dear Candidate,</p>
          <p>We are contacting you from the Recruitment Department at Marna Financing Company to invite you for an in-person interview on <strong>${interview_time}</strong> corresponding to <strong>${interview_date}</strong>.</p>
          <p>Please bring your updated resume with you.</p>
          <p>Thank you.</p>
        </body>
      </html>
    `;
  }

  const payload = {
    subject,
    html_body: emailBody,
    email,
  };

  try {
    const response = await sendEmailApi(payload);
    if (typeof onSuccess === "function") onSuccess(response);
    return response;
  } catch (err) {
    console.error("❌ Failed to send first interview email:", err);
    if (typeof onError === "function") onError(err);
    throw err;
  }
};

// export const sendFirstInterviewEmail = async ({
//   candidate_name,
//   interview_date,
//   interview_time,
//   email,
//   interviewTypeField,
//   interviewUrlField,
//   interviewLocationField,
//   onSuccess = null,
//   onError = null,
// }) => {
//   const emailBody = `
//     <html>
//       <body style="font-family: Arial, sans-serif; color: #333;">
//         <h3>First Interview Invitation – MRNA</h3>
//         <p>Dear ${candidate_name},</p>
//         <p>You are invited to attend the first interview for the position at MRNA.</p>
//         <p><strong>Date:</strong> ${interview_date}</p>
//         <p><strong>Time:</strong> ${interview_time}</p>
//         <p>Please confirm your availability.</p>
//         <p>Best regards,<br/>HR Manager<br/>MRNA<br/>support@mrna.sa</p>
//       </body>
//     </html>
//   `;

//   const payload = {
//     subject: "First Interview Invitation – MRNA | دعوة للمقابلة الأولى – MRNA",
//     html_body: emailBody,
//     email,
//   };

//   try {
//     const response = await sendEmailApi(payload);
//     console.log("First interview email sent!", response);
//     if (typeof onSuccess === "function") onSuccess(response);
//     return response;
//   } catch (err) {
//     console.error("Failed to send first interview email:", err);
//     if (typeof onError === "function") onError(err);
//     throw err;
//   }
// };

// export const sendFirstInterviewEmail = async ({ candidate_name, interview_date, interview_time, email, onSuccess = null, onError = null }) => {
//   const emailBody = `<html>...first interview body...</html>`;

//   const payload = {
//     subject: "First Interview Invitation – MRNA",
//     html_body: emailBody,
//     email,
//   };

//   return sendEmailApi(payload)
//     .then((res) => { if (onSuccess) onSuccess(res); return res; })
//     .catch((err) => { if (onError) onError(err); throw err; });
// };

export const sendSecondInterviewEmail = async ({
  candidate_name,
  interview_date,
  interview_time,
  email,
  interviewTypeField,
  interviewUrlField,
  interviewLocationField,
  onSuccess = null,
  onError = null,
}) => {
  const emailBody = `<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            color: #333;
            padding: 20px;
        }
        .container {
            background-color: #ffffff;
            border-radius: 8px;
            padding: 30px;
            max-width: 600px;
            margin: 0 auto;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
        }
        .header {
            text-align: center;
            color: #2c3e50;
        }
        .button {
            background-color: #3498db;
            color: white;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 5px;
            display: inline-block;
        }
        .footer {
            text-align: center;
            font-size: 12px;
            color: #777;
            margin-top: 30px;
        }
    </style>
</head>
<body>
    <div class="container">
        
        <!-- Arabic Version -->
        <div class="header">
            <h2>دعوة للمقابلة الثانية &ndash; MRNA</h2>
        </div>
        <p>عزيزي/عزيزتي ${candidate_name},</p>
        <p>تهانينا مرة أخرى! نحن متحمسون لدعوتك للمقابلة الثانية للمنصب في MRNA. هذه هي الخطوة التالية في عملية التوظيف لدينا، ونحن حريصون على معرفة المزيد عن مهاراتك وخبراتك.</p>

        <p>يرجى العثور على تفاصيل المقابلة أدناه:</p>
        <ul>
            <li><strong>تاريخ المقابلة:</strong> ${interview_date}</li>
            <li><strong>الوقت:</strong> ${interview_time}</li>
            <li><strong>${
              interviewTypeField === "online"
                ? `<strong>موقع المقابلة: ${interviewUrlField} </strong>`
                : `<strong>رابط المقابلة: ${interviewLocationField}</strong>`
            }</strong></li>
        </ul>

        <p>يرجى تأكيد توفر الوقت للمقابلة بالرد على هذا البريد الإلكتروني. إذا كان الوقت المحدد غير مناسب لك، يرجى إعلامنا بتوفر الوقت المناسب لك، وسنبذل قصارى جهدنا لتلبية احتياجاتك.</p>

        <p>نوصي بأن تستعد لمناقشة مفصلة عن خبرتك وكيف يمكن أن تساهم في فريقنا. إذا كان لديك أي أسئلة أو تحتاج إلى مساعدة، فلا تتردد في الاتصال بنا على support@mrna.sa.</p>

        <p>نتطلع إلى لقائك قريباً!</p>

        <p>مع أطيب التحيات,<br>
        مدير الموارد البشرية<br>
        MRNA<br>
        support@mrna.sa</p>

        <div class="footer">
            <p>شكراً لاهتمامك بالانضمام إلى mrna.sa.</p>
        </div>

        <!-- English Version -->
        <div class="header">
            <h2>Second Interview Invitation &ndash; MRNA</h2>
        </div>
        <p>Dear ${candidate_name},</p>
        <p>Congratulations once again! We are excited to invite you for a second interview for the position at MRNA. This is the next step in our recruitment process, and we are eager to learn more about your skills and experience.</p>
        
        <p>Please find the interview details below:</p>
        <ul>
            <li><strong>Interview Date:</strong> ${interview_date}</li>
            <li><strong>Time:</strong> ${interview_time}</li>
            <li><strong>${
              interviewTypeField === "online"
                ? `<strong>Interview Link: ${interviewUrlField} </strong>`
                : `<strong>Interview Location: ${interviewLocationField}</strong>`
            }</strong></li>
        </ul>

        <p>Please confirm your availability for the interview by replying to this email. If the scheduled time does not work for you, kindly let us know your availability, and we will do our best to accommodate you.</p>

        <p>We recommend that you prepare for a detailed discussion about your experience and how you could contribute to our team. If you have any questions or need assistance, please do not hesitate to reach out to us at support@mrna.sa.</p>

        <p>We look forward to meeting you soon!</p>

        <p>Best regards,<br>
        HR Manager<br>
        MRNA<br>
        support@mrna.sa</p>

        <div class="footer">
            <p>Thank you for your interest in joining mrna.sa.</p>
        </div>

    </div>
</body>
</html>
`;

  const payload = {
    subject: "Second Interview Invitation MRNA | دعوة للمقابلة الثانية – MRNA",
    html_body: emailBody,
    email,
  };

  return sendEmailApi(payload)
    .then((res) => {
      if (onSuccess) onSuccess(res);
      return res;
    })
    .catch((err) => {
      if (onError) onError(err);
      throw err;
    });
};

export const sendThirdInterviewEmail = async ({
  candidate_name,
  interview_date,
  interview_time,
  email,
  interviewTypeField,
  interviewUrlField,
  interviewLocationField,
  onSuccess = null,
  onError = null,
}) => {
  const emailBody = `
  <!DOCTYPE html>
  <html>
  <head>
      <style>
          body {
              font-family: Arial, sans-serif;
              background-color: #f4f4f4;
              color: #333;
              padding: 20px;
          }
          .container {
              background-color: #ffffff;
              border-radius: 8px;
              padding: 30px;
              max-width: 600px;
              margin: 0 auto;
              box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
          }
          .header {
              text-align: center;
              color: #2c3e50;
          }
          .button {
              background-color: #3498db;
              color: white;
              padding: 10px 20px;
              text-decoration: none;
              border-radius: 5px;
              display: inline-block;
          }
          .footer {
              text-align: center;
              font-size: 12px;
              color: #777;
              margin-top: 30px;
          }
      </style>
  </head>
  <body>
      <div class="container">
          
          <!-- Arabic Version -->
          <div class="header">
              <h2>دعوة للمقابلة الثالثة &ndash; MRNA</h2>
          </div>
          <p>عزيزي/عزيزتي ${candidate_name},</p>
          <p>تهانينا مرة أخرى! نحن متحمسون لدعوتك للمقابلة الثالثة للمنصب في MRNA. هذه هي الخطوة التالية في عملية التوظيف لدينا، ونحن حريصون على معرفة المزيد عن مهاراتك وخبراتك.</p>

          <p>يرجى العثور على تفاصيل المقابلة أدناه:</p>
          <ul>
              <li><strong>تاريخ المقابلة:</strong> ${interview_date}</li>
              <li><strong>الوقت:</strong> ${interview_time}</li>
              <li><strong>${
                interviewTypeField === "online"
                  ? `<strong>موقع المقابلة: ${interviewUrlField} </strong>`
                  : `<strong>رابط المقابلة: ${interviewLocationField}</strong>`
              }</strong></li>
          </ul>

          <p>يرجى تأكيد توفر الوقت للمقابلة بالرد على هذا البريد الإلكتروني. إذا كان الوقت المحدد غير مناسب لك، يرجى إعلامنا بتوفر الوقت المناسب لك، وسنبذل قصارى جهدنا لتلبية احتياجاتك.</p>

          <p>نوصي بأن تستعد لمناقشة مفصلة عن خبرتك وكيف يمكن أن تساهم في فريقنا. إذا كان لديك أي أسئلة أو تحتاج إلى مساعدة، فلا تتردد في الاتصال بنا على support@mrna.sa.</p>

          <p>نتطلع إلى لقائك قريباً!</p>

          <p>مع أطيب التحيات,<br>
          مدير الموارد البشرية<br>
          MRNA<br>
          support@mrna.sa</p>

          <div class="footer">
              <p>شكراً لاهتمامك بالانضمام إلى mrna.sa.</p>
          </div>

          <!-- English Version -->
          <div class="header">
              <h2>Third Interview Invitation &ndash; MRNA</h2>
          </div>
          <p>Dear ${candidate_name},</p>
          <p>Congratulations once again! We are excited to invite you for a third interview for the position at MRNA. This is the next step in our recruitment process, and we are eager to learn more about your skills and experience.</p>
          
          <p>Please find the interview details below:</p>
          <ul>
              <li><strong>Interview Date:</strong> ${interview_date}</li>
              <li><strong>Time:</strong> ${interview_time}</li>
              <li><strong>${
                interviewTypeField === "online"
                  ? `<strong>Interview Link: ${interviewUrlField} </strong>`
                  : `<strong>Interview Location: ${interviewLocationField}</strong>`
              }</strong></li>
          </ul>

          <p>Please confirm your availability for the interview by replying to this email. If the scheduled time does not work for you, kindly let us know your availability, and we will do our best to accommodate you.</p>

          <p>We recommend that you prepare for a detailed discussion about your experience and how you could contribute to our team. If you have any questions or need assistance, please do not hesitate to reach out to us at support@mrna.sa.</p>

          <p>We look forward to meeting you soon!</p>

          <p>Best regards,<br>
          HR Manager<br>
          MRNA<br>
          support@mrna.sa</p>

          <div class="footer">
              <p>Thank you for your interest in joining mrna.sa.</p>
          </div>

      </div>
  </body>
  </html>
`;

  const payload = {
    subject: "Third Interview Invitation MRNA | دعوة للمقابلة الثالثة – MRNA",
    html_body: emailBody,
    email,
  };

  return sendEmailApi(payload)
    .then((res) => {
      if (onSuccess) onSuccess(res);
      return res;
    })
    .catch((err) => {
      if (onError) onError(err);
      throw err;
    });
};

export const sendInterviewerEmail = async ({
  candidateName,
  interviewerName,
  interviewDate,
  interviewTime,
  candidateEmail,
  email,
  interviewTypeField,
  interviewUrlField,
  interviewLocationField,
  onSuccess = null,
  onError = null,
}) => {
  const emailBody = `
  <!DOCTYPE html>
  <html>
  <head>
      <style>
          body {
              font-family: Arial, sans-serif;
              background-color: #f4f4f4;
              color: #333;
              padding: 20px;
          }
          .container {
              background-color: #ffffff;
              border-radius: 8px;
              padding: 30px;
              max-width: 600px;
              margin: 0 auto;
              box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
          }
          .header {
              text-align: center;
              color: #2c3e50;
          }
          .button {
              background-color: #3498db;
              color: white;
              padding: 10px 20px;
              text-decoration: none;
              border-radius: 5px;
              display: inline-block;
          }
          .footer {
              text-align: center;
              font-size: 12px;
              color: #777;
              margin-top: 30px;
          }
      </style>
  </head>
  <body>
      <div class="container">
          
          <!-- Arabic Version -->
          <div class="header">
              <h2>تفاصيل المقابلة للمرشح  – MRNA</h2>
          </div>
          <p>عزيزي/عزيزتي ${interviewerName},</p>
          <p>نود إبلاغك بأنه تم تحديد موعد مقابلة للمرشح ${candidateName} - ${candidateEmail} MRNA. هذه هي الخطوة التالية في عملية التوظيف لدينا، ونحن حريصون على معرفة المزيد عن مهاراته وخبراته.</p>

          <p>إليك تفاصيل المقابلة:</p>
          <ul>
              <li><strong>تاريخ المقابلة:</strong> ${interviewDate}</li>
              <li><strong>الوقت:</strong> ${interviewTime}</li>
              <li><strong>اسم المرشح:</strong> ${candidateName} - ${candidateEmail}</li>
              <li><strong>${
                interviewTypeField === "online"
                  ? `<strong>موقع المقابلة: ${interviewUrlField} </strong>`
                  : `<strong>رابط المقابلة: ${interviewLocationField}</strong>`
              }</strong></li>
          </ul>

          <p>يرجى التأكد من تحضير الأسئلة والملاحظات المطلوبة للمقابلة. إذا كانت لديك أي أسئلة أو تحتاج إلى مزيد من المعلومات، لا تتردد في الاتصال بنا على support@mrna.sa.</p>

          <p>نتمنى لك مقابلة ناجحة!</p>

          <p>مع أطيب التحيات,<br>
          مدير الموارد البشرية<br>
          MRNA<br>
          support@mrna.sa</p>

          <div class="footer">
              <p>شكراً لاهتمامك في الانضمام إلى MRNA.</p>
          </div>

          <!-- English Version -->
          <div class="header">
              <h2>Interview Details for Candidate – MRNA</h2>
          </div>
          <p>Dear ${interviewerName},</p>
          <p>We would like to inform you that an interview has been scheduled for candidate ${candidateName} - ${candidateEmail} at MRNA. This is the next step in our recruitment process, and we are eager to learn more about their skills and experience.</p>

          <p>Please find the interview details below:</p>
          <ul>
              <li><strong>Interview Date:</strong> ${interviewDate}</li>
              <li><strong>Time:</strong> ${interviewTime}</li>
              <li><strong>Candidate Name:</strong> ${candidateName} - ${candidateEmail}</li>
              <li><strong>${
                interviewTypeField === "online"
                  ? `<strong>Interview Link: ${interviewUrlField} </strong>`
                  : `<strong>Interview Location: ${interviewLocationField}</strong>`
              }</strong></li>

          </ul>

          <p>Please ensure to prepare the necessary questions and notes for the interview. If you have any questions or need further information, feel free to reach out to us at support@mrna.sa.</p>

          <p>We wish you a successful interview!</p>

          <p>Best regards,<br>
          HR Manager<br>
          MRNA<br>
          support@mrna.sa</p>

          <div class="footer">
              <p>Thank you for your interest in joining MRNA.</p>
          </div>

      </div>
  </body>
  </html>
`;

  const payload = {
    subject:
      "Interview Details for Candidate – MRNA | تفاصيل المقابلة للمرشح  – MRNA",
    html_body: emailBody,
    email,
  };

  return sendEmailApi(payload)
    .then((res) => {
      if (onSuccess) onSuccess(res);
      return res;
    })
    .catch((err) => {
      if (onError) onError(err);
      throw err;
    });
};

export const sendCandidateRejectEmail = async ({
  candidate_name,
  candidateEmail,
  onSuccess = null,
  onError = null,
}) => {
  const emailBody = `
    <html>
      <body style="font-family: Arial, sans-serif; color: #333;">
        <table
          dir="ltr"
          width="100%"
          cellSpacing={0}
          cellPadding={8}
          style={{ borderCollapse: "collapse", border: "1px solid #000" }}
        >
          <tbody>

            <tr>
              <td style={{ borderBottom: "1px solid #000" }}>
                Job Application Status
              </td>
            </tr>

            <tr>
              <td style={{ borderBottom: "1px solid #000" }}>
                <p>Dear Candidate ${candidate_name}</p>

                <p>Thank you for your interest in joining the Mrna Finance team. We regret to   inform you that you have not been selected for the next step of the   recruitment process.
                Your experience and skills are appreciated, but they do not meet the needs   of the current position. We appreciate your time and effort and would like to   inform you that we wish to retain your information for future   opportunities.
                </p>

                <p>Thank you.</p>
              </td>
            </tr>
          </tbody>
        </table>

        <br />

        
        <table
          dir="ltr"
          width="100%"
          cellSpacing={0}
          cellPadding={8}
          style={{ borderCollapse: "collapse", border: "1px solid #000" }}
        >
          <tbody>
            
            <tr>
              <td style={{ borderBottom: "1px solid #000" }} dir="rtl">
                حالة طلب التوظيف
              </td>
            </tr>

            
            <tr>
              <td dir="rtl" style={{ whiteSpace: "pre-wrap" }}>
                {/* Provided Arabic body (you can replace with a dynamic variable if needed) */}
                <p>عزيزنا المرشح/ة ${candidate_name} </p>
                    <p>
                    نشكرك على رغبتك بالانضمام الى فريق عمل مرنة للتمويل، يؤسفنا ابلاغك بعدم   اختيارك للمرحلة التالية من عملية التوظيف
                    خبراتك و مهاراتك محل تقدير لكنها لا تتناسب مع احتياج الشاغر الحالي، نقدر   وقتك و جهدك و نبلغك برغبتنا بالاحتفاظ بمعلوماتك في حال وجود فرص مستقبلية   مناسبة .
                    </p>
                    <p>مع الشكر . </p>
              </td>
            </tr>
          </tbody>
        </table>
      </body>
    </html>
  `;

  const payload = {
    subject: "Job Application Status – MRNA | حالة طلب التوظيف – MRNA",
    html_body: emailBody,
    candidateEmail,
  };

  try {
    const response = await sendEmailApi(payload);
    if (typeof onSuccess === "function") onSuccess(response);
    return response;
  } catch (err) {
    console.error("Failed to send Rejection email:", err);
    if (typeof onError === "function") onError(err);
    throw err;
  }
};

/**
 * -------------------
 * Contract Refused
 * -------------------
 */
export const sendContractRefusedEmail = async ({
  candidateName,
  creatorName,
  approvalStatus,
  rejectionName,
  rejectionEmail,
  rejectionReason,
  email,
  onSuccess = null,
  onError = null,
}) => {
  const emailBody = `
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f4f4f4;
                color: #333;
                padding: 20px;
            }
            .container {
                background-color: #ffffff;
                border-radius: 8px;
                padding: 30px;
                max-width: 600px;
                margin: 0 auto;
                box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
            }
            .header {
                text-align: center;
                color: #2c3e50;
            }
            .footer {
                text-align: center;
                font-size: 12px;
                color: #777;
                margin-top: 30px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            
            <div class="header">
                <h2>تفاصيل الموافقة على عرض الوظيفة</h2>
            </div>
            <p>عزيزي/عزيزتي ${creatorName},</p>
            <p>نود إبلاغك بأن عرض الوظيفة للمرشح ${candidateName} قد تم مراجعته من قبل الفرق المعنية. إليك حالته الحالية: ${rejectionName}</p>

            <p><strong>حالة الموافقة:</strong> ${approvalStatus}</p>

            ${
              rejectionReason
                ? `<p><strong>سبب الرفض:</strong> ${rejectionReason}</p>`
                : ""
            }

            <p>إذا كان لديك أي أسئلة أو تحتاج إلى مزيد من التوضيح، يرجى الاتصال بنا على ${rejectionEmail}.</p>

            <p>مع أطيب التحيات,<br>مدير الموارد البشرية<br>MRNA<br>support@mrna.sa</p>

            <div class="footer">
                <p>شكرًا لاهتمامك في عملية التوظيف لدينا MRNA.</p>
            </div>

            <div class="header">
                <h2>Offer Letter Approval Status </h2>
            </div>
            <p>Dear ${creatorName},</p>
            <p>We would like to inform you that the offer letter for candidate ${candidateName} has been reviewed by ${rejectionName}. Below is the current status:</p>

            <p><strong>Approval Status:</strong> ${approvalStatus}</p>

            ${
              rejectionReason
                ? `<p><strong>Reason for Rejection:</strong> ${rejectionReason}</p>`
                : ""
            }


            <p>If you have any questions or need further clarification, please do not hesitate to reach out to us at ${rejectionEmail}.</p>

            <p>Best regards,<br>HR Manager<br>MRNA<br>support@mrna.sa</p>

            <div class="footer">
                <p>Thank you for your interest in our hiring process MRNA.</p>
            </div>

        </div>
    </body>
    </html>
`;

  const payload = {
    subject:
      "offer Letter Approval Status – MRNA | تفاصيل الموافقة على عرض الوظيفة  – MRNA",
    html_body: emailBody,
    email,
  };

  return sendEmailApi(payload)
    .then((res) => {
      if (onSuccess) onSuccess(res);
      return res;
    })
    .catch((err) => {
      if (onError) onError(err);
      throw err;
    });
};

/**
 * -------------------
 * Task + Work Email Notifications
 * -------------------
 */
export const sendNewTaskEmail = async ({
  email,
  onSuccess = null,
  onError = null,
}) => {
  const emailBody = `
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            color: #333;
            padding: 20px;
        }
        .container {
            background-color: #ffffff;
            border-radius: 8px;
            padding: 30px;
            max-width: 600px;
            margin: 0 auto;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
        }
        .header {
            text-align: center;
            color: #2c3e50;
        }
        .footer {
            text-align: center;
            font-size: 12px;
            color: #777;
            margin-top: 30px;
        }
    </style>
</head>
<body>
    <div class="container">
        
        <!-- Arabic Version -->
        <div class="header">
            <h2>لديك مهمة جديدة – يرجى التحقق من قائمة المهام الخاصة بك</h2>
        </div>
        <p>عزيزي/عزيزتي،</p>
        <p>نود إعلامك بأنه قد تم إضافة مهمة جديدة إلى قائمة مهامك. يرجى التحقق من قائمة المهام الخاصة بك في النظام.</p>

        <p>يرجى مراجعة المهمة وإتمامها في الوقت المحدد. إذا كان لديك أي أسئلة أو تحتاج إلى مساعدة إضافية، لا تتردد في الاتصال بنا.</p>

        <p>مع أطيب التحيات,<br>
        فريق العمل<br>
        support@company.com</p>

        <div class="footer">
            <p>شكراً لاهتمامك في متابعة المهام.</p>
        </div>

        <!-- English Version -->
        <div class="header">
            <h2>You Have a New Task – Please Check Your Task List</h2>
        </div>
        <p>Dear,</p>
        <p>We would like to inform you that a new task has been added to your task list. Please check your task list in the system.</p>

        <p>Please review and complete the task on time. If you have any questions or need further assistance, feel free to contact us.</p>

        <p>Best regards,<br>
        The Team<br>
        support@company.com</p>

        <div class="footer">
            <p>Thank you for your attention to your tasks.</p>
        </div>

    </div>
</body>
</html>
`;

  const payload = {
    subject: "You Have a New Task  – MRNA | لديك مهمة جديدة – MRNA",
    html_body: emailBody,
    email,
  };

  return sendEmailApi(payload)
    .then((res) => {
      if (onSuccess) onSuccess(res);
      return res;
    })
    .catch((err) => {
      if (onError) onError(err);
      throw err;
    });
};

export const sendWorkEmailNotification = async ({
  email,
  workEmail,
  onSuccess = null,
  onError = null,
}) => {
  const emailBody = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      color: #333;
      padding: 20px;
    }
    .container {
      background-color: #ffffff;
      border-radius: 8px;
      padding: 30px;
      max-width: 600px;
      margin: 0 auto;
      box-shadow: 0 4px 10px rgba(0,0,0,0.1);
    }
    .header {
      text-align: center;
      color: #2c3e50;
      margin-bottom: 20px;
    }
    .footer {
      text-align: center;
      font-size: 12px;
      color: #777;
      margin-top: 30px;
    }
    .info {
      background-color: #eef6fc;
      padding: 15px;
      border-left: 4px solid #3498db;
      margin: 20px 0;
      word-break: break-all;
    }
  </style>
</head>
<body>
  <div class="container">
    <!-- Arabic Version -->
    <div class="header">
      <h2>تم تعيين بريدك الوظيفي</h2>
    </div>
    <p>مرحباً،</p>
    <p>نود إعلامك بأنه قد تم تعيين بريدك الوظيفي التالي:</p>
    <div class="info">${workEmail}</div>
    <p>يرجى استخدام هذا البريد لتسجيل الدخول إلى بوابة الموظفين للوصول إلى نظامنا الداخلي.</p>
    <p>إذا واجهت أي مشكلة في تسجيل الدخول، لا تتردد في التواصل معنا.</p>
    <p>مع أطيب التحيات،<br/>فريق الدعم<br/>support@company.com</p>
    <div class="footer">
      <p>شكراً لك على انضمامك إلينا.</p>
    </div>

    <!-- English Version -->
    <div class="header">
      <h2>Your Work Email Has Been Assigned</h2>
    </div>
    <p>Hi there,</p>
    <p>We’re pleased to let you know that your new work email has been set up:</p>
    <div class="info">${workEmail}</div>
    <p>Please use this email address to log in to the Employee Portal and access our internal systems.</p>
    <p>If you encounter any issues signing in, feel free to reach out to us for assistance.</p>
    <p>Best regards,<br/>The Support Team<br/>support@company.com</p>
    <div class="footer">
      <p>Thank you for joining us!</p>
    </div>
  </div>
</body>
</html>
`;

  const payload = {
    subject: `Your Work Email Has Been Assigned – تم تعيين بريدك الوظيفي`,
    html_body: emailBody,
    email,
  };

  return sendEmailApi(payload)
    .then((res) => {
      if (onSuccess) onSuccess(res);
      return res;
    })
    .catch((err) => {
      if (onError) onError(err);
      throw err;
    });
};


// ============================================================
// Transaction email functions (from transactionsEmailSender.js)
// ============================================================

export const requestsEmailSender = async ({
  emails,
  emailSubject,
  requestType,
  employeeName,
  employeeId,
  requestData,
  onSuccess = null,
  onError = null,
}) => {
  const selectedTemplate =
    requestEmailTemplates[requestType] ||
    (() =>
      `<p>${employeeName} (Employee ID: ${employeeId}) has submitted a ${requestType}.</p>`);


  const emailBody = `
  <!DOCTYPE html>
  <html>
  <head>
    <style>
      body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        color: #333;
        padding: 20px;
      }
      .container {
        background-color: #ffffff;
        border-radius: 8px;
        padding: 30px;
        max-width: 600px;
        margin: 0 auto;
        box-shadow: 0 4px 10px rgba(0,0,0,0.1);
      }
      .header {
        text-align: center;
        color: #2c3e50;
        margin-bottom: 20px;
      }
      .footer {
        text-align: center;
        font-size: 12px;
        color: #777;
        margin-top: 30px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      ${selectedTemplate(employeeName, employeeId, requestData)}
      <div class="footer">
        <p>This is an automated message. Please do not reply.</p>
      </div>
    </div>
  </body>
  </html>
  `;

  // ${selectedTemplate(employeeName, employeeId, requestData?.start_date, requestData?.end_date)}

  const payload = {
    subject: emailSubject,
    html_body: emailBody,
    email: emails,
  };

  return sendEmailApi(payload)
    .then((res) => {
      if (onSuccess) onSuccess(res);
      return res;
    })
    .catch((err) => {
      if (onError) onError(err);
      throw err;
    });
};

// export const approvalEmailSender = async ({
//   email,
//   approvalPayload,
//   approvalType,
//   approverName,
//   approverRole,
//   onSuccess = null,
//   onError = null,
// }) => {



//   let content = `Your request has been approved by the ${approverName} ${approverRole}`;
//   let emailSubject = `Approval for the ${approvalType.split("_")[0]}`;
//   let userRole =
//     approverRole === "hr_manager"
//       ? "HR Manager"
//       : approverRole === "hr"
//       ? "HR"
//       : approverRole === "manager"
//       ? "Manager"
//       : approverRole;

//   if (approvalType === "leave_requests") {
//     content = `Your ${approvalPayload?.leave_type} has been approved by ${approverName} ${approverRole}`;
//     emailSubject = `Approval for the ${approvalPayload?.leave_type}`;
//   } else if (approvalType === "allowance_requests") {
//     content = `Your ticket request for amount ${approvalPayload?.amount} which was requested on the date ${approvalPayload?.requested_date} has been approved by the ${userRole}, ${approverName}`;
//     emailSubject = `Approval for the Allowance Request`;
//   }

//   const emailBody = `
//   <!DOCTYPE html>
//   <html>
//   <head>
//     <style>
//       body {
//         font-family: Arial, sans-serif;
//         background-color: #f4f4f4;
//         color: #333;
//         padding: 20px;
//       }
//       .container {
//         background-color: #ffffff;
//         border-radius: 8px;
//         padding: 30px;
//         max-width: 600px;
//         margin: 0 auto;
//         box-shadow: 0 4px 10px rgba(0,0,0,0.1);
//       }
//       .header {
//         text-align: center;
//         color: #2c3e50;
//         margin-bottom: 20px;
//       }
//       .footer {
//         text-align: center;
//         font-size: 12px;
//         color: #777;
//         margin-top: 30px;
//       }
//     </style>
//   </head>
//   <body>
//     <div class="container">
//       <p>${content}</p>
//       <div class="footer">
//         <p>This is an automated message. Please do not reply.</p>
//       </div>
//     </div>
//   </body>
//   </html>
//   `;

//   const payload = {
//     subject: emailSubject,
//     html_body: emailBody,
//     email: email,
//   };

//   return sendEmailApi(payload)
//     .then((res) => {
//       if (onSuccess) onSuccess(res);
//       return res;
//     })
//     .catch((err) => {
//       if (onError) onError(err);
//       throw err;
//     });
// };


export const approvalEmailSender = async ({
  email,
  approvalPayload,
  approvalType,
  approverName,
  approverRole,
  onSuccess = null,
  onError = null,
}) => {
  // Normalize role name
  let userRole =
    approverRole === "hr_manager"
      ? "HR Manager"
      : approverRole === "hr"
      ? "HR"
      : approverRole === "hod"
      ? "HOD"
      : approverRole === "manager"
      ? "Manager"
      : approverRole;

  // Default content & subject
  let content = `Your ${approvalType.replace(/_/g, " ")} has been approved by ${userRole}, ${approverName}.`;
  let emailSubject = `Approval Notification - ${approvalType.replace(/_/g, " ")}`;

  // ✅ Special case: pay_stopage
  if (approvalType === "pay_stopage") {
    content = `Your pay stoppage request has been approved by ${userRole}, ${approverName}. Salary processing will reflect this update.`;
    emailSubject = `Approval Notification - Pay Stoppage`;
  }
   else if (approvalType === "leave_requests") {
    content = `Your ${approvalPayload?.leave_type} has been approved by ${approverName} ${approverRole}`;
    emailSubject = `Approval for the ${approvalPayload?.leave_type}`;
  } else if (approvalType === "allowance_requests") {
    content = `Your ticket request for amount ${approvalPayload?.amount} which was requested on the date ${approvalPayload?.requested_date} has been approved by the ${userRole}, ${approverName}`;
    emailSubject = `Approval for the Allowance Request`;
  }
  // ✅ Special case: resignation_request
  else if (approvalType === "resignation_request") {
    content = `Your resignation request has been approved by ${userRole}, ${approverName}. Kindly follow up with HR for the clearance and exit process.`;
    emailSubject = `Approval Notification - Resignation Request`;
  }
  // ✅ Generic case (all others)
  else {
    content = `Your ${approvalType.replace(/_/g, " ")} has been approved by ${userRole}, ${approverName}.`;
    emailSubject = `Approval Notification - ${approvalType.replace(/_/g, " ")}`;
  }

  // ✅ Single HTML template
  const emailBody = `
  <!DOCTYPE html>
  <html>
  <head>
    <style>
      body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        color: #333;
        padding: 20px;
      }
      .container {
        background-color: #ffffff;
        border-radius: 8px;
        padding: 30px;
        max-width: 600px;
        margin: 0 auto;
        box-shadow: 0 4px 10px rgba(0,0,0,0.1);
      }
      .header {
        text-align: center;
        color: #2c3e50;
        font-size: 20px;
        margin-bottom: 20px;
      }
      .content {
        font-size: 15px;
        line-height: 1.5;
      }
      .footer {
        text-align: center;
        font-size: 12px;
        color: #777;
        margin-top: 30px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">Approval Notification</div>
      <div class="content">
        <p>${content}</p>
      </div>
      <div class="footer">
        <p>This is an automated message. Please do not reply.</p>
      </div>
    </div>
  </body>
  </html>
  `;

  const payload = {
    subject: emailSubject,
    html_body: emailBody,
    email,
    // email: "zeeshanmrna@yopmail.com"
  };

  return sendEmailApi(payload)
    .then((res) => {
      onSuccess?.(res);
      return res;
    })
    .catch((err) => {
      onError?.(err);
      throw err;
    });
};

export const rejectionEmailSender = async ({
  email,
  rejectPayload,
  rejectionType,
  rejectorName,
  reason,
  rejectorRole,
  onSuccess = null,
  onError = null,
}) => {
  // Normalize role name
  let userRole =
    rejectorRole === "hr_manager"
      ? "HR Manager"
      : rejectorRole === "hr"
      ? "HR"
      : rejectorRole === "hod"
      ? "HOD"
      : rejectorRole === "manager"
      ? "Manager"
      : rejectorRole;

  // Default content & subject
  let content = `Your ${rejectionType.replace(/_/g, " ")} has been rejected by ${userRole}, ${rejectorName}${
    reason ? ` for the reason: ${reason}` : ""
  }.`;
  let emailSubject = `Rejection Notification - ${rejectionType.replace(/_/g, " ")}`;

  // ✅ Special case: pay_stopage
  if (rejectionType === "pay_stopage") {
    content = `Your pay stoppage request has been rejected by ${userRole}, ${rejectorName}${
      reason ? ` for the reason: ${reason}` : ""
    }. Please contact HR/Finance for clarification.`;
    emailSubject = `Rejection Notification - Pay Stoppage`;
  }
  // ✅ Special case: resignation_request
  else if (rejectionType === "resignation_request") {
    content = `Your resignation request has been rejected by ${userRole}, ${rejectorName}${
      reason ? ` for the reason: ${reason}` : ""
    }. Kindly follow up with HR for further details.`;
    emailSubject = `Rejection Notification - Resignation Request`;
  }
    else if (rejectionType === "leave_requests") {
    content = `Your ${rejectPayload?.leave_type} has been rejected by ${rejectorName} ${rejectorRole} for the reason: ${reason}`;
    emailSubject = `Rejection for the ${rejectPayload?.leave_type}`;
  } else if (rejectionType === "allowance_requests") {
    content = `Your ticket request for amount ${rejectPayload?.amount} which was requested on the date ${rejectPayload?.requested_date} has been Rejected by the ${userRole}, ${rejectorName} due to the reason: ${reason}`;
    emailSubject = `Rejection for the Allowance Request`;
  }
  // ✅ Generic fallback (all others)
  else {
    content = `Your ${rejectionType.replace(/_/g, " ")} has been rejected by ${userRole}, ${rejectorName}${
      reason ? ` for the reason: ${reason}` : ""
    }.`;
    emailSubject = `Rejection Notification - ${rejectionType.replace(/_/g, " ")}`;
  }

  // ✅ Single HTML template
  const emailBody = `
  <!DOCTYPE html>
  <html>
  <head>
    <style>
      body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        color: #333;
        padding: 20px;
      }
      .container {
        background-color: #ffffff;
        border-radius: 8px;
        padding: 30px;
        max-width: 600px;
        margin: 0 auto;
        box-shadow: 0 4px 10px rgba(0,0,0,0.1);
      }
      .header {
        text-align: center;
        color: #c0392b;
        font-size: 20px;
        margin-bottom: 20px;
      }
      .content {
        font-size: 15px;
        line-height: 1.5;
      }
      .footer {
        text-align: center;
        font-size: 12px;
        color: #777;
        margin-top: 30px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">Rejection Notification</div>
      <div class="content">
        <p>${content}</p>
      </div>
      <div class="footer">
        <p>This is an automated message. Please do not reply.</p>
      </div>
    </div>
  </body>
  </html>
  `;

  const payload = {
    subject: emailSubject,
    html_body: emailBody,
    email,
    // email: "zeeshanmrna@yopmail.com"
  };

  return sendEmailApi(payload)
    .then((res) => {
      onSuccess?.(res);
      return res;
    })
    .catch((err) => {
      onError?.(err);
      throw err;
    });
};



// export const rejectionEmailSender = async ({
//   email,
//   rejectPayload,
//   rejectionType,
//   rejectorName,
//   reason,
//   rejectorRole,
//   onSuccess = null,
//   onError = null,
// }) => {
//   let content = `Your request has been Rejected by the ${rejectorName} ${rejectorRole}`;
//   let emailSubject = `Rejection for the ${rejectionType.split("_")[0]}`;
//   let userRole =
//     rejectorRole === "hr_manager"
//       ? "HR Manager"
//       : rejectorRole === "hr"
//       ? "HR"
//        : approverRole === "hod"
//       ? "HOD"
//       : rejectorRole === "manager"
//       ? "Manager"
//       : rejectorRole;

//   if (rejectionType === "leave_requests") {
//     content = `Your ${rejectPayload?.leave_type} has been rejected by ${rejectorName} ${rejectorRole} for the reason: ${reason}`;
//     emailSubject = `Rejection for the ${rejectPayload?.leave_type}`;
//   } else if (rejectionType === "allowance_requests") {
//     content = `Your ticket request for amount ${rejectPayload?.amount} which was requested on the date ${rejectPayload?.requested_date} has been Rejected by the ${userRole}, ${rejectorName} due to the reason: ${reason}`;
//     emailSubject = `Rejection for the Allowance Request`;
//   }

//   const emailBody = `
//   <!DOCTYPE html>
//   <html>
//   <head>
//     <style>
//       body {
//         font-family: Arial, sans-serif;
//         background-color: #f4f4f4;
//         color: #333;
//         padding: 20px;
//       }
//       .container {
//         background-color: #ffffff;
//         border-radius: 8px;
//         padding: 30px;
//         max-width: 600px;
//         margin: 0 auto;
//         box-shadow: 0 4px 10px rgba(0,0,0,0.1);
//       }
//       .header {
//         text-align: center;
//         color: #2c3e50;
//         margin-bottom: 20px;
//       }
//       .footer {
//         text-align: center;
//         font-size: 12px;
//         color: #777;
//         margin-top: 30px;
//       }
//     </style>
//   </head>
//   <body>
//     <div class="container">
//       <p>${content}</p>
//       <div class="footer">
//         <p>This is an automated message. Please do not reply.</p>
//       </div>
//     </div>
//   </body>
//   </html>
//   `;
  
//   const payload = {
//     subject: emailSubject,
//     html_body: emailBody,
//     email: email,
//   };

//   return sendEmailApi(payload)
//     .then((res) => {
//       if (onSuccess) onSuccess(res);
//       return res;
//     })
//     .catch((err) => {
//       if (onError) onError(err);
//       throw err;
//     });
// };

export const transactionApprovalEmailSenderToFinance = async (
  email,
  approvalPayload,
  approvalType,
  approverName,
  approverRole,
  onSuccess = null,
  onError = null
) => {
  const emailSubject = `Allowance Request Approved`;

  let userRole =
    approverRole === "hr_manager"
      ? "HR Manager"
      : approverRole === "hr"
      ? "HR"
      : approverRole === "manager"
      ? "Manager"
      : approverRole;

  const emailBody = `
  <!DOCTYPE html>
  <html>
  <head>
    <style>
      body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        color: #333;
        padding: 20px;
      }
      .container {
        background-color: #ffffff;
        border-radius: 8px;
        padding: 30px;
        max-width: 600px;
        margin: 0 auto;
        box-shadow: 0 4px 10px rgba(0,0,0,0.1);
      }
      .header {
        text-align: center;
        color: #2c3e50;
        margin-bottom: 20px;
      }
      .footer {
        text-align: center;
        font-size: 12px;
        color: #777;
        margin-top: 30px;
      }
    </style>
  </head>
  <body>
      <p>Dear Finance Manager,</p>

      <p>I hope this email finds you well.</p>

      <p>
        Please be informed that the <strong>allowance request</strong> has been
        <strong>approved by the ${userRole} ${approverName}</strong> of amount <strong>${approvalPayload?.amount}</strong> requested on ${approvalPayload?.requested_date} and is now ready for
        processing by the Finance Department.
      </p>

      <div class="footer">
        <p>This is an automated message. Please do not reply.</p>
      </div>
    </div>
  </body>
  </html>
  `;

  const payload = {
    subject: emailSubject,
    html_body: emailBody,
    email: email,
  };

  return sendEmailApi(payload)
    .then((res) => {
      if (onSuccess) onSuccess(res);
      return res;
    })
    .catch((err) => {
      if (onError) onError(err);
      throw err;
    });
};
